#!/bin/sh
MAKE_OPTION=-j

FLASH=flash

make clean

# TARGET
#
# TARGET=ADC0
# TARGET=ADC0Temperature
# TARGET=HelloWorld
# TARGET=LED
# TARGET=LCD
# TARGET=MachineTimer
# TARGET=SPI0-ST7789V
# TARGET=USART

#FreeRTOS TARGET
#
KERNEL=FreeRTOS
KERNEL_VERSION=FreeRTOS-KernelV10.6.1
# #
# TARGET=FreeRTOSQueue
# TARGET=FreeRTOSSemaphoreBinary
# TARGET=FreeRTOSSemaphoreCounting
# TARGET=FreeRTOSSemaphoreMutex
# TARGET=FreeRTOSTask
# TARGET=FreeRTOSTemplate
TARGET=FreeRTOSTimer

make $MAKE_OPTION TARGET=$TARGET KERNEL=$KERNEL KERNEL_VERSION=$KERNEL_VERSION $FLASH